inherits:
  - strictness_veryhigh

output-format: grouped

pep8:
  none: true

# We only provide 1 function, this is a bit useless
doc-warnings: false

# Only enabled for pyflakes
test-warnings: false

dodgy:
  run: true
profile-validator:
  run: true
pyflakes:
  run: true
pylint:
  run: true
pyroma:
  run: true

# Not needed
mccabe:
  run: false
# Enabled in python 3 in tox
mypy:
  run: false

ignore-paths:
  - venv
  - .tox
  - docs
  - example
  - tests/integration
  - build
  - .pytest_cache
  - tavern.egg_info
